#!/usr/bin/env python3
"""Fetch ``devices.json`` from the newest radiofrequency release.

``devices.json`` is generated by ``radiofrequency/scripts/export_web_devices.py``
from the YAML profiles that repo owns. It must never be hand-edited here, and
the release bundle must never ship the copy committed under ``www/`` — see
``docs/decisions/001-devices-json-from-upstream-release.md``.

Usage::

    python3 scripts/fetch_devices_json.py                  # -> stdout
    python3 scripts/fetch_devices_json.py -o www/devices.json

Exits non-zero with a specific message when the upstream release, the asset, or
the payload's shape is missing. There is deliberately no fall-back to the
committed copy: a stale bundle that looks healthy is the failure this whole
extraction exists to prevent.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from collections.abc import Callable

UPSTREAM_REPO = "tclancy/radiofrequency"
ASSET_NAME = "devices.json"
DEFAULT_API_ROOT = "https://api.github.com"

#: Injected I/O. ``GetJson`` reads a GitHub API endpoint; ``GetBytes`` reads an
#: asset URL. Both are parameters rather than module globals so the tests
#: exercise the real parsing and validation code against fake transports.
GetJson = Callable[[str], object]
GetBytes = Callable[[str], bytes]


class FetchError(RuntimeError):
    """Anything that stops us producing a trustworthy devices.json."""


def api_root() -> str:
    """The GitHub API base URL.

    ``GITHUB_API_URL`` is set by GitHub Actions itself (and differs on GHES), so
    honouring it is the idiomatic behaviour rather than a test hook — though the
    release-bundle integration test does point it at a local stub.
    """
    return os.environ.get("GITHUB_API_URL", DEFAULT_API_ROOT).rstrip("/")


def _auth_headers() -> dict[str, str]:
    """Bearer header when a token is present, plain otherwise.

    radiofrequency is public today, so anonymous reads work. A token is still
    used when available: it raises the rate limit and keeps this working
    unchanged if the repo is ever made private.
    """
    headers = {"Accept": "application/vnd.github+json"}
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _urlopen_json(url: str) -> object:
    request = urllib.request.Request(url, headers=_auth_headers())
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def _urlopen_bytes(url: str) -> bytes:
    headers = dict(_auth_headers(), Accept="application/octet-stream")
    authorization = headers.pop("Authorization", None)
    request = urllib.request.Request(url, headers=headers)
    if authorization:
        # Unredirected: the asset URL 302s to a pre-signed CDN host that needs
        # no auth, and urllib would otherwise forward the bearer token across
        # that cross-host hop. Pre-signed means nothing is lost by dropping it.
        request.add_unredirected_header("Authorization", authorization)
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def latest_release(repo: str, get_json: GetJson) -> dict:
    """Return the newest published release for ``repo``.

    Raises ``FetchError`` when the repo has no releases — which is the state
    radiofrequency is in until a ``v``-prefixed tag is pushed, so the message
    names that fix explicitly.
    """
    try:
        payload = get_json(f"{api_root()}/repos/{repo}/releases/latest")
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            raise FetchError(
                f"{repo} has no published releases. Its release workflow is gated on "
                "tags matching 'v*'; a bare '0.1.0' tag does not fire it. Fix upstream "
                "with: git tag v0.1.0 <sha> && git push origin v0.1.0"
            ) from exc
        raise FetchError(f"GitHub API error {exc.code} reading {repo} releases") from exc
    if not isinstance(payload, dict):
        raise FetchError(f"Unexpected releases payload for {repo}: {type(payload).__name__}")
    return payload


def asset_url(release: dict, name: str) -> str:
    """Return the API download URL for the named asset on ``release``."""
    assets = release.get("assets") or []
    for asset in assets:
        if asset.get("name") == name:
            url = asset.get("url")
            if not url:
                raise FetchError(f"Asset {name!r} on {release.get('tag_name')} has no URL")
            return url
    available = ", ".join(sorted(a.get("name", "?") for a in assets)) or "(none)"
    raise FetchError(
        f"Release {release.get('tag_name')!r} has no {name!r} asset. Present: {available}"
    )


def parse(raw: bytes) -> dict:
    """Decode the payload, rejecting anything that is not a JSON object.

    Split out from ``validate`` so a transport failure that returns an HTML
    login page reads as "not JSON" rather than as a schema complaint.
    """
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise FetchError(f"devices.json is not valid JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise FetchError(f"devices.json must be an object, got {type(payload).__name__}")
    return payload


def validate_light(light: object, where: str) -> None:
    """Shape-check one lamp entry against what ``www/app.js`` dereferences.

    Upstream's publish script already checks ``unit`` and ``commands``. This
    checks the half app.js actually reads — ``label`` for the row caption and
    both ``commands.on`` / ``commands.off`` for the buttons — because a payload
    that satisfies the producer can still render a card whose buttons POST
    ``undefined``.
    """
    if not isinstance(light, dict):
        raise FetchError(f"{where} is not an object")
    for field in ("unit", "label"):
        if not light.get(field):
            raise FetchError(f"{where} is missing {field!r}")
    commands = light.get("commands")
    if not isinstance(commands, dict):
        raise FetchError(f"{where} ({light['unit']}) has no commands object")
    for command in ("on", "off"):
        payload = commands.get(command)
        if not payload:
            raise FetchError(f"{where} ({light['unit']}) is missing the {command!r} command")
        # app.js POSTs this object to /api/transmit verbatim, so `pulses` is the
        # whole message. An empty list publishes cleanly and transmits nothing —
        # the same silent-no-op class this function exists to catch.
        if not isinstance(payload, dict) or not payload.get("pulses"):
            raise FetchError(f"{where} ({light['unit']}) {command!r} command has no pulses")


def validate(raw: bytes) -> dict:
    """Parse and shape-check a ``devices.json`` payload. Returns it on success."""
    payload = parse(raw)
    lights = payload.get("lights")
    if not isinstance(lights, list) or not lights:
        raise FetchError("devices.json has no lights")
    for index, light in enumerate(lights):
        validate_light(light, f"lights[{index}]")
    return payload


def fetch_devices_json(
    repo: str = UPSTREAM_REPO,
    get_json: GetJson | None = None,
    get_bytes: GetBytes | None = None,
) -> tuple[bytes, str]:
    """Return ``(raw_bytes, tag_name)`` for the newest upstream ``devices.json``."""
    get_json = _urlopen_json if get_json is None else get_json
    get_bytes = _urlopen_bytes if get_bytes is None else get_bytes

    release = latest_release(repo, get_json)
    url = asset_url(release, ASSET_NAME)
    try:
        raw = get_bytes(url)
    except urllib.error.HTTPError as exc:
        raise FetchError(f"Could not download {ASSET_NAME}: HTTP {exc.code}") from exc
    validate(raw)
    return raw, str(release.get("tag_name", "unknown"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", default=UPSTREAM_REPO, help="upstream repo (owner/name)")
    parser.add_argument("-o", "--output", help="write here instead of stdout")
    args = parser.parse_args(argv)

    try:
        raw, tag = fetch_devices_json(args.repo)
    except FetchError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.output:
        with open(args.output, "wb") as handle:
            handle.write(raw)
        print(f"Wrote {args.output} from {args.repo} release {tag}", file=sys.stderr)
    else:
        sys.stdout.buffer.write(raw)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
